package com.arete.korbly.modules.termsheet.enums;

public enum CPCode {
    CORP_CERT_INCORPORATION, CORP_CONSTITUTIONAL_DOCS, CORP_GOOD_STANDING_CERT,
    CORP_BOARD_RESOLUTION_BORROW, CORP_OFFICER_CERT_SAMPLE_SIGS, CORP_POWER_OF_ATTORNEY,

    KYC_BORROWER_COMPLETE, KYC_DIRECTORS_UBOS, KYC_SOURCE_OF_FUNDS_DECL, KYC_SANCTIONS_SCREEN_CLEAR,

    FIN_AUDITED_FS_LATEST, FIN_MGMT_ACCOUNTS_YTD, FIN_CASHFLOW_PROJECTIONS, FIN_TAX_CLEARANCE_CERT,

    SEC_SECURITY_AGREEMENTS_EXECUTED, SEC_DEBENTURE_MORTGAGE_EXECUTED, SEC_PERFECTION_FILINGS_COMPLETE,
    SEC_COLLATERAL_REGISTRATION_PROOF, SEC_STAMPING_DUTY_PAID, SEC_VALUATION_REPORTS, SEC_INSPECTION_REPORTS,
    SEC_SHARE_CHARGE_REGISTERED, SEC_LAND_CHARGE_REGISTERED,

    INS_POLICY_BOUND, INS_COI_PROVIDED, INS_LOSS_PAYEE_ENDORSEMENT, INS_MIN_COVERAGE_LIMITS_MET, INS_BROKER_LETTER,

    CONSENT_EXISTING_LENDER_NOC, CONSENT_LANDLORD_WAREHOUSE, CONSENT_GOVT_REGULATOR,
    CONSENT_INTERCREDITOR_EXECUTED, CONSENT_SUBORDINATION_AGREEMENT,

    BANK_DEBT_SERVICE_RESERVE_FUNDED, BANK_COLLECTION_ACCOUNT_OPENED,
    BANK_ACCOUNT_CONTROL_AGREEMENT, BANK_ESCROW_AGREEMENT_EXECUTED,

    LEGAL_OPINION_ENFORCEABILITY, LEGAL_OPINION_PERFECTED_SECURITY, LEGAL_FILINGS_COMPLETED, LEGAL_GOVERNING_LAW_OK,

    FEE_UPFRONT_PAID, FEE_LEGAL_COSTS_PAID, FEE_STAMPING_REGISTRATION_FEES_PAID,

    DOC_LOAN_AGREEMENT_EXECUTED, DOC_TERM_SHEET_EXECUTED, DOC_COVENANT_SCHEDULES_DELIVERED,
    DOC_REPRESENTATIONS_BROUGHT_DOWN, DOC_NO_DEFAULT_CERTIFICATE,

    OTHER_ESG_QUESTIONNAIRE_COMPLETE, OTHER_ENV_PERMITS_LICENCES, OTHER_PROJECT_DOCS_KEY_CONTRACTS,
    OTHER_BOARD_MINUTES_NOTED
}
